import type { JsonSchema } from "../../core/types.ts";

import { s } from "../../core/json-schema.ts";

export type PaperclipMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

export interface PaperclipOperation {
  name: string;
  description: string;
  method: PaperclipMethod;
  path: string;
  pathFields: readonly string[];
  queryFields: readonly string[];
  bodyFields: readonly string[];
  bodyObjectField?: string;
  defaultBody?: unknown;
  outputField: string;
  inputSchema: JsonSchema;
  outputSchema: JsonSchema;
}

const companyId = s.uuid("The Paperclip company ID.");
const projectId = s.uuid("The Paperclip project ID.");
const agentId = s.uuid("The Paperclip agent ID.");
const issueId = s.uuid("The Paperclip issue ID.");
const routineId = s.uuid("The Paperclip routine ID.");
const triggerId = s.uuid("The Paperclip routine trigger ID.");
const skillId = s.uuid("The Paperclip company skill ID.");
const objectResult = (description: string) => s.unknownObject(description);
const listResult = (description: string) => s.array(description, s.unknownObject("One Paperclip record."));
const wrappedOutput = (field: string, description: string, value: JsonSchema) =>
  s.actionOutput({ [field]: value }, description);

const projectBody = s.looseRequiredObject(
  "The Paperclip project to create. Extra fields supported by the connected Paperclip version are preserved.",
  {
    name: s.nonWhitespaceString("The project name."),
    description: s.nullableString("The project description."),
    status: s.stringEnum("The project status.", ["backlog", "planned", "in_progress", "completed", "cancelled"]),
    leadAgentId: s.nullable(agentId),
    targetDate: s.nullableString("The target date."),
    color: s.nullableString("The project color."),
  },
  { optional: ["description", "status", "leadAgentId", "targetDate", "color"] },
);

const issueBody = s.looseRequiredObject(
  "The Paperclip issue to create. Extra fields supported by the connected Paperclip version are preserved.",
  {
    title: s.nonWhitespaceString("The issue title."),
    description: s.nullableString("The issue description."),
    status: s.stringEnum("The initial issue status.", [
      "backlog",
      "todo",
      "in_progress",
      "in_review",
      "done",
      "blocked",
      "cancelled",
    ]),
    priority: s.stringEnum("The issue priority.", ["critical", "high", "medium", "low"]),
    workMode: s.stringEnum("The issue work mode.", ["standard", "ask", "planning", "skill_test"]),
    projectId: s.nullable(projectId),
    goalId: s.nullable(s.uuid("The goal ID.")),
    parentId: s.nullable(issueId),
    assigneeAgentId: s.nullable(agentId),
    assigneeUserId: s.nullableString("The board-user assignee ID."),
    labelIds: s.array("Label IDs to attach.", s.uuid("One label ID.")),
    blockedByIssueIds: s.array("Issue IDs that block this issue.", issueId),
  },
  {
    optional: [
      "description",
      "status",
      "priority",
      "workMode",
      "projectId",
      "goalId",
      "parentId",
      "assigneeAgentId",
      "assigneeUserId",
      "labelIds",
      "blockedByIssueIds",
    ],
  },
);

const skillBody = s.looseRequiredObject(
  "The inline Paperclip skill to create. Extra fields supported by the connected Paperclip version are preserved.",
  {
    name: s.nonWhitespaceString("The skill name."),
    slug: s.nullableString("An optional stable skill slug."),
    description: s.nullableString("The skill description."),
    markdown: s.nullableString("The SKILL.md content."),
    categories: s.stringArray("Skill categories."),
  },
  { optional: ["slug", "description", "markdown", "categories"] },
);

const routineBody = s.looseRequiredObject(
  "The Paperclip routine to create. Its description becomes the issue brief when the routine runs. Extra fields supported by the connected Paperclip version are preserved.",
  {
    title: s.nonWhitespaceString("The routine title.", { maxLength: 200 }),
    description: s.nullableString("The work brief placed on issues created by this routine."),
    projectId: s.nullable(projectId),
    goalId: s.nullable(s.uuid("The goal ID.")),
    parentIssueId: s.nullable(issueId),
    assigneeAgentId: s.nullable(agentId),
    priority: s.stringEnum("The issue priority used by the routine.", ["critical", "high", "medium", "low"]),
    status: s.stringEnum("The routine status.", ["active", "paused", "archived"]),
    concurrencyPolicy: s.stringEnum("How overlapping routine runs are handled.", [
      "coalesce_if_active",
      "always_enqueue",
      "skip_if_active",
    ]),
    catchUpPolicy: s.stringEnum("How missed scheduled runs are handled.", ["skip_missed", "enqueue_missed_with_cap"]),
  },
  {
    optional: [
      "description",
      "projectId",
      "goalId",
      "parentIssueId",
      "assigneeAgentId",
      "priority",
      "status",
      "concurrencyPolicy",
      "catchUpPolicy",
    ],
  },
);

const triggerBody = s.looseRequiredObject(
  "The trigger to add to a Paperclip routine. Extra fields supported by the connected Paperclip version are preserved.",
  {
    kind: s.stringEnum("The trigger kind.", ["schedule", "webhook", "api"]),
    label: s.nullableString("A human-readable trigger label."),
    enabled: s.boolean("Whether the trigger is enabled."),
    cronExpression: s.nonWhitespaceString("A standard five-field cron expression for a schedule trigger."),
    timezone: s.nonWhitespaceString("An IANA timezone for a schedule trigger."),
    signingMode: s.stringEnum("The webhook signing mode.", ["bearer", "hmac_sha256", "github_hmac", "none"]),
    replayWindowSec: s.integer("The webhook replay window in seconds.", { minimum: 30, maximum: 86_400 }),
  },
  { optional: ["label", "enabled", "cronExpression", "timezone", "signingMode", "replayWindowSec"] },
);

export const paperclipOperations: readonly PaperclipOperation[] = [
  {
    name: "get_session",
    description: "Get the signed-in Paperclip board user's current session and profile.",
    method: "GET",
    path: "/api/auth/get-session",
    pathFields: [],
    queryFields: [],
    bodyFields: [],
    outputField: "session",
    inputSchema: s.actionInput({}),
    outputSchema: wrappedOutput("session", "The current Paperclip board-user session.", objectResult("Session data.")),
  },
  {
    name: "list_companies",
    description: "List Paperclip companies accessible to the signed-in board user.",
    method: "GET",
    path: "/api/companies",
    pathFields: [],
    queryFields: [],
    bodyFields: [],
    outputField: "companies",
    inputSchema: s.actionInput({}),
    outputSchema: wrappedOutput("companies", "The accessible Paperclip companies.", listResult("Company records.")),
  },
  {
    name: "list_projects",
    description: "List projects in a Paperclip company.",
    method: "GET",
    path: "/api/companies/{companyId}/projects",
    pathFields: ["companyId"],
    queryFields: [],
    bodyFields: [],
    outputField: "projects",
    inputSchema: s.actionInput({ companyId }, ["companyId"]),
    outputSchema: wrappedOutput("projects", "The company's Paperclip projects.", listResult("Project records.")),
  },
  {
    name: "get_project",
    description: "Get one Paperclip project.",
    method: "GET",
    path: "/api/projects/{projectId}",
    pathFields: ["projectId"],
    queryFields: [],
    bodyFields: [],
    outputField: "project",
    inputSchema: s.actionInput({ projectId }, ["projectId"]),
    outputSchema: wrappedOutput("project", "The requested Paperclip project.", objectResult("Project data.")),
  },
  {
    name: "create_project",
    description: "Create a project in a Paperclip company as the signed-in board user.",
    method: "POST",
    path: "/api/companies/{companyId}/projects",
    pathFields: ["companyId"],
    queryFields: [],
    bodyFields: [],
    bodyObjectField: "project",
    outputField: "project",
    inputSchema: s.actionInput({ companyId, project: projectBody }, ["companyId", "project"]),
    outputSchema: wrappedOutput("project", "The created Paperclip project.", objectResult("Project data.")),
  },
  {
    name: "update_project",
    description: "Update fields on a Paperclip project.",
    method: "PATCH",
    path: "/api/projects/{projectId}",
    pathFields: ["projectId"],
    queryFields: [],
    bodyFields: [],
    bodyObjectField: "changes",
    outputField: "project",
    inputSchema: s.actionInput(
      {
        projectId,
        changes: s.unknownObject("Project fields to update, using the connected Paperclip version's schema."),
      },
      ["projectId", "changes"],
    ),
    outputSchema: wrappedOutput("project", "The updated Paperclip project.", objectResult("Project data.")),
  },
  {
    name: "list_agents",
    description:
      "List agents in a Paperclip company. This reads agent records; the connector itself remains a board user.",
    method: "GET",
    path: "/api/companies/{companyId}/agents",
    pathFields: ["companyId"],
    queryFields: [],
    bodyFields: [],
    outputField: "agents",
    inputSchema: s.actionInput({ companyId }, ["companyId"]),
    outputSchema: wrappedOutput("agents", "The company's Paperclip agents.", listResult("Agent records.")),
  },
  {
    name: "get_agent",
    description: "Get one Paperclip agent.",
    method: "GET",
    path: "/api/agents/{agentId}",
    pathFields: ["agentId"],
    queryFields: [],
    bodyFields: [],
    outputField: "agent",
    inputSchema: s.actionInput({ agentId }, ["agentId"]),
    outputSchema: wrappedOutput("agent", "The requested Paperclip agent.", objectResult("Agent data.")),
  },
  {
    name: "update_agent",
    description: "Update general fields on a Paperclip agent as a board user.",
    method: "PATCH",
    path: "/api/agents/{agentId}",
    pathFields: ["agentId"],
    queryFields: [],
    bodyFields: [],
    bodyObjectField: "changes",
    outputField: "agent",
    inputSchema: s.actionInput(
      {
        agentId,
        changes: s.unknownObject("Agent fields to update, using the connected Paperclip version's schema."),
      },
      ["agentId", "changes"],
    ),
    outputSchema: wrappedOutput("agent", "The updated Paperclip agent.", objectResult("Agent data.")),
  },
  {
    name: "pause_agent",
    description: "Pause a Paperclip agent.",
    method: "POST",
    path: "/api/agents/{agentId}/pause",
    pathFields: ["agentId"],
    queryFields: [],
    bodyFields: [],
    outputField: "agent",
    inputSchema: s.actionInput({ agentId }, ["agentId"]),
    outputSchema: wrappedOutput("agent", "The paused Paperclip agent.", objectResult("Agent data.")),
  },
  {
    name: "resume_agent",
    description: "Resume a paused Paperclip agent.",
    method: "POST",
    path: "/api/agents/{agentId}/resume",
    pathFields: ["agentId"],
    queryFields: [],
    bodyFields: [],
    outputField: "agent",
    inputSchema: s.actionInput({ agentId }, ["agentId"]),
    outputSchema: wrappedOutput("agent", "The resumed Paperclip agent.", objectResult("Agent data.")),
  },
  {
    name: "get_agent_skills",
    description:
      "Get an agent's skill snapshot, including the complete desiredSkills list needed before a replacement sync.",
    method: "GET",
    path: "/api/agents/{agentId}/skills",
    pathFields: ["agentId"],
    queryFields: [],
    bodyFields: [],
    outputField: "skills",
    inputSchema: s.actionInput({ agentId }, ["agentId"]),
    outputSchema: wrappedOutput("skills", "The agent's Paperclip skill snapshot.", objectResult("Skill data.")),
  },
  {
    name: "sync_agent_skills",
    description:
      "Add, remove, or replace an agent's desired Paperclip skills. Replacement overwrites the complete desired skill list, so call get_agent_skills first.",
    method: "POST",
    path: "/api/agents/{agentId}/skills/sync",
    pathFields: ["agentId"],
    queryFields: [],
    bodyFields: ["mode", "desiredSkills"],
    outputField: "skills",
    inputSchema: s.actionInput(
      {
        agentId,
        mode: s.stringEnum("How to apply desiredSkills. Use replace only with the complete desired skill list.", [
          "add",
          "remove",
          "replace",
        ]),
        desiredSkills: s.array(
          "Skill keys or version-pinned skill selections to add, remove, or use as the full replacement.",
          s.anyOf("One desired skill selection.", [
            s.nonWhitespaceString("A Paperclip skill key."),
            s.looseRequiredObject("A version-pinned skill selection.", {
              key: s.nonWhitespaceString("The Paperclip skill key."),
              versionId: s.nullable(s.uuid("The skill version ID.")),
            }),
          ]),
        ),
      },
      ["agentId", "mode", "desiredSkills"],
    ),
    outputSchema: wrappedOutput("skills", "The updated agent skill snapshot.", objectResult("Skill data.")),
  },
  {
    name: "list_issues",
    description: "List issues in a Paperclip company with common filters and pagination.",
    method: "GET",
    path: "/api/companies/{companyId}/issues",
    pathFields: ["companyId"],
    queryFields: [
      "status",
      "priority",
      "projectId",
      "assigneeAgentId",
      "assigneeUserId",
      "q",
      "limit",
      "offset",
      "sortField",
      "sortDir",
      "updatedSince",
    ],
    bodyFields: [],
    outputField: "issues",
    inputSchema: s.actionInput(
      {
        companyId,
        status: s.nonWhitespaceString("A status or comma-separated status filter."),
        priority: s.nonWhitespaceString("A priority filter."),
        projectId,
        assigneeAgentId: agentId,
        assigneeUserId: s.nonWhitespaceString("A board-user ID or me."),
        q: s.nonWhitespaceString("A text search query."),
        limit: s.integer("The maximum number of issues to return.", { minimum: 1 }),
        offset: s.integer("The zero-based issue offset.", { minimum: 0 }),
        sortField: s.nonWhitespaceString("The Paperclip issue sort field."),
        sortDir: s.stringEnum("The sort direction.", ["asc", "desc"]),
        updatedSince: s.dateTime("Only include issues updated since this timestamp."),
      },
      ["companyId"],
    ),
    outputSchema: wrappedOutput(
      "issues",
      "The Paperclip issue-list response, including pagination metadata when supplied by the instance.",
      s.unknown("Issue list data."),
    ),
  },
  {
    name: "get_issue",
    description: "Get one Paperclip issue with its available board-user detail.",
    method: "GET",
    path: "/api/issues/{issueId}",
    pathFields: ["issueId"],
    queryFields: [],
    bodyFields: [],
    outputField: "issue",
    inputSchema: s.actionInput({ issueId }, ["issueId"]),
    outputSchema: wrappedOutput("issue", "The requested Paperclip issue.", objectResult("Issue data.")),
  },
  {
    name: "create_issue",
    description: "Create an issue in a Paperclip company as the signed-in board user.",
    method: "POST",
    path: "/api/companies/{companyId}/issues",
    pathFields: ["companyId"],
    queryFields: [],
    bodyFields: [],
    bodyObjectField: "issue",
    outputField: "issue",
    inputSchema: s.actionInput({ companyId, issue: issueBody }, ["companyId", "issue"]),
    outputSchema: wrappedOutput("issue", "The created Paperclip issue.", objectResult("Issue data.")),
  },
  {
    name: "update_issue",
    description: "Update fields on a Paperclip issue as the signed-in board user.",
    method: "PATCH",
    path: "/api/issues/{issueId}",
    pathFields: ["issueId"],
    queryFields: [],
    bodyFields: [],
    bodyObjectField: "changes",
    outputField: "issue",
    inputSchema: s.actionInput(
      {
        issueId,
        changes: s.unknownObject("Issue fields to update, using the connected Paperclip version's schema."),
      },
      ["issueId", "changes"],
    ),
    outputSchema: wrappedOutput("issue", "The updated Paperclip issue.", objectResult("Issue data.")),
  },
  {
    name: "list_issue_comments",
    description: "List comments on a Paperclip issue.",
    method: "GET",
    path: "/api/issues/{issueId}/comments",
    pathFields: ["issueId"],
    queryFields: ["after", "order", "limit"],
    bodyFields: [],
    outputField: "comments",
    inputSchema: s.actionInput(
      {
        issueId,
        after: s.nonWhitespaceString("Only return comments after this comment ID."),
        order: s.stringEnum("The comment order.", ["asc", "desc"]),
        limit: s.integer("The maximum number of comments to return.", { minimum: 1 }),
      },
      ["issueId"],
    ),
    outputSchema: wrappedOutput("comments", "The issue comments.", listResult("Comment records.")),
  },
  {
    name: "add_issue_comment",
    description: "Add a comment to a Paperclip issue as the signed-in board user.",
    method: "POST",
    path: "/api/issues/{issueId}/comments",
    pathFields: ["issueId"],
    queryFields: [],
    bodyFields: ["body", "reopen", "resume", "interrupt"],
    outputField: "comment",
    inputSchema: s.actionInput(
      {
        issueId,
        body: s.nonEmptyString("The comment body."),
        reopen: s.boolean("Whether to reopen a closed issue."),
        resume: s.boolean("Whether to resume blocked work."),
        interrupt: s.boolean("Whether to interrupt an active run. Board users only."),
      },
      ["issueId", "body"],
    ),
    outputSchema: wrappedOutput("comment", "The created Paperclip issue comment.", objectResult("Comment data.")),
  },
  {
    name: "list_skills",
    description: "List company-managed Paperclip skills.",
    method: "GET",
    path: "/api/companies/{companyId}/skills",
    pathFields: ["companyId"],
    queryFields: ["q", "sort", "scope", "folderId", "includeSubtree"],
    bodyFields: [],
    outputField: "skills",
    inputSchema: s.actionInput(
      {
        companyId,
        q: s.nonWhitespaceString("A skill search query."),
        sort: s.nonWhitespaceString("The Paperclip skill sort mode."),
        scope: s.nonWhitespaceString("The Paperclip skill scope filter."),
        folderId: s.uuid("The skill folder ID."),
        includeSubtree: s.boolean("Whether to include descendant folders."),
      },
      ["companyId"],
    ),
    outputSchema: wrappedOutput("skills", "The company's Paperclip skills.", s.unknown("Skill list data.")),
  },
  {
    name: "get_skill_files",
    description: "Read a file from a company-managed Paperclip skill. Defaults to SKILL.md.",
    method: "GET",
    path: "/api/companies/{companyId}/skills/{skillId}/files",
    pathFields: ["companyId", "skillId"],
    queryFields: ["path"],
    bodyFields: [],
    outputField: "file",
    inputSchema: s.actionInput(
      {
        companyId,
        skillId,
        path: s.nonWhitespaceString("The relative skill file path. Defaults to SKILL.md."),
      },
      ["companyId", "skillId"],
    ),
    outputSchema: wrappedOutput("file", "The requested Paperclip skill file.", objectResult("Skill file data.")),
  },
  {
    name: "create_skill",
    description: "Create an inline company-managed Paperclip skill.",
    method: "POST",
    path: "/api/companies/{companyId}/skills",
    pathFields: ["companyId"],
    queryFields: [],
    bodyFields: [],
    bodyObjectField: "skill",
    outputField: "skill",
    inputSchema: s.actionInput({ companyId, skill: skillBody }, ["companyId", "skill"]),
    outputSchema: wrappedOutput("skill", "The created Paperclip skill.", objectResult("Skill data.")),
  },
  {
    name: "update_skill_file",
    description: "Create or replace one file in a company-managed Paperclip skill.",
    method: "PATCH",
    path: "/api/companies/{companyId}/skills/{skillId}/files",
    pathFields: ["companyId", "skillId"],
    queryFields: [],
    bodyFields: ["path", "content"],
    outputField: "file",
    inputSchema: s.actionInput(
      {
        companyId,
        skillId,
        path: s.nonWhitespaceString("The relative skill file path."),
        content: s.string("The complete file content."),
      },
      ["companyId", "skillId", "path", "content"],
    ),
    outputSchema: wrappedOutput("file", "The updated Paperclip skill file.", objectResult("Skill file data.")),
  },
  {
    name: "import_skill",
    description:
      "Import a skill directory that already exists on the Paperclip server. The source path is resolved by Paperclip, not Open Connector.",
    method: "POST",
    path: "/api/companies/{companyId}/skills/import",
    pathFields: ["companyId"],
    queryFields: [],
    bodyFields: ["source"],
    outputField: "skill",
    inputSchema: s.actionInput(
      { companyId, source: s.nonWhitespaceString("The absolute skill-directory path on the Paperclip server.") },
      ["companyId", "source"],
    ),
    outputSchema: wrappedOutput("skill", "The imported Paperclip skill.", objectResult("Skill data.")),
  },
  {
    name: "list_routines",
    description: "List routines in a Paperclip company.",
    method: "GET",
    path: "/api/companies/{companyId}/routines",
    pathFields: ["companyId"],
    queryFields: ["projectId"],
    bodyFields: [],
    outputField: "routines",
    inputSchema: s.actionInput({ companyId, projectId }, ["companyId"]),
    outputSchema: wrappedOutput("routines", "The company's Paperclip routines.", listResult("Routine records.")),
  },
  {
    name: "get_routine",
    description: "Get one Paperclip routine with its triggers.",
    method: "GET",
    path: "/api/routines/{routineId}",
    pathFields: ["routineId"],
    queryFields: [],
    bodyFields: [],
    outputField: "routine",
    inputSchema: s.actionInput({ routineId }, ["routineId"]),
    outputSchema: wrappedOutput("routine", "The requested Paperclip routine.", objectResult("Routine data.")),
  },
  {
    name: "create_routine",
    description: "Create a Paperclip routine that produces assigned issues when triggered.",
    method: "POST",
    path: "/api/companies/{companyId}/routines",
    pathFields: ["companyId"],
    queryFields: [],
    bodyFields: [],
    bodyObjectField: "routine",
    outputField: "routine",
    inputSchema: s.actionInput({ companyId, routine: routineBody }, ["companyId", "routine"]),
    outputSchema: wrappedOutput("routine", "The created Paperclip routine.", objectResult("Routine data.")),
  },
  {
    name: "update_routine",
    description: "Update fields on a Paperclip routine.",
    method: "PATCH",
    path: "/api/routines/{routineId}",
    pathFields: ["routineId"],
    queryFields: [],
    bodyFields: [],
    bodyObjectField: "changes",
    outputField: "routine",
    inputSchema: s.actionInput(
      {
        routineId,
        changes: s.unknownObject("Routine fields to update, using the connected Paperclip version's schema."),
      },
      ["routineId", "changes"],
    ),
    outputSchema: wrappedOutput("routine", "The updated Paperclip routine.", objectResult("Routine data.")),
  },
  {
    name: "list_routine_runs",
    description: "List recent runs for a Paperclip routine.",
    method: "GET",
    path: "/api/routines/{routineId}/runs",
    pathFields: ["routineId"],
    queryFields: ["limit"],
    bodyFields: [],
    outputField: "runs",
    inputSchema: s.actionInput(
      { routineId, limit: s.integer("The maximum number of routine runs to return.", { minimum: 1 }) },
      ["routineId"],
    ),
    outputSchema: wrappedOutput("runs", "Recent Paperclip routine runs.", listResult("Routine run records.")),
  },
  {
    name: "create_routine_trigger",
    description: "Add a schedule, webhook, or API trigger to a Paperclip routine.",
    method: "POST",
    path: "/api/routines/{routineId}/triggers",
    pathFields: ["routineId"],
    queryFields: [],
    bodyFields: [],
    bodyObjectField: "trigger",
    outputField: "trigger",
    inputSchema: s.actionInput({ routineId, trigger: triggerBody }, ["routineId", "trigger"]),
    outputSchema: wrappedOutput("trigger", "The created Paperclip routine trigger.", objectResult("Trigger data.")),
  },
  {
    name: "update_routine_trigger",
    description: "Update a Paperclip routine trigger.",
    method: "PATCH",
    path: "/api/routine-triggers/{triggerId}",
    pathFields: ["triggerId"],
    queryFields: [],
    bodyFields: [],
    bodyObjectField: "changes",
    outputField: "trigger",
    inputSchema: s.actionInput(
      {
        triggerId,
        changes: s.unknownObject("Trigger fields to update, using the connected Paperclip version's schema."),
      },
      ["triggerId", "changes"],
    ),
    outputSchema: wrappedOutput("trigger", "The updated Paperclip routine trigger.", objectResult("Trigger data.")),
  },
  {
    name: "delete_routine_trigger",
    description: "Delete a Paperclip routine trigger.",
    method: "DELETE",
    path: "/api/routine-triggers/{triggerId}",
    pathFields: ["triggerId"],
    queryFields: [],
    bodyFields: [],
    outputField: "result",
    inputSchema: s.actionInput({ triggerId }, ["triggerId"]),
    outputSchema: wrappedOutput("result", "The Paperclip deletion response.", s.unknown("Deletion result.")),
  },
  {
    name: "run_routine",
    description: "Manually trigger a Paperclip routine and create its issue.",
    method: "POST",
    path: "/api/routines/{routineId}/run",
    pathFields: ["routineId"],
    queryFields: [],
    bodyFields: [],
    bodyObjectField: "run",
    defaultBody: { source: "manual" },
    outputField: "run",
    inputSchema: s.actionInput(
      {
        routineId,
        run: s.looseObject("Optional routine-run inputs such as variables, payload, projectId, or assigneeAgentId.", {
          source: s.stringEnum("The run source.", ["manual", "api"]),
          variables: s.record("Routine variable values.", s.unknown("One variable value.")),
          payload: s.record("An optional trigger payload.", s.unknown("One payload value.")),
          idempotencyKey: s.nullableString("An optional idempotency key."),
        }),
      },
      ["routineId"],
    ),
    outputSchema: wrappedOutput("run", "The triggered Paperclip routine run.", objectResult("Routine run data.")),
  },
  {
    name: "list_secrets",
    description: "List Paperclip company secret metadata. Secret values are not returned by this endpoint.",
    method: "GET",
    path: "/api/companies/{companyId}/secrets",
    pathFields: ["companyId"],
    queryFields: [],
    bodyFields: [],
    outputField: "secrets",
    inputSchema: s.actionInput({ companyId }, ["companyId"]),
    outputSchema: wrappedOutput("secrets", "The company's Paperclip secret metadata.", listResult("Secret records.")),
  },
  {
    name: "create_secret",
    description: "Create a Paperclip-managed company secret as the signed-in board user.",
    method: "POST",
    path: "/api/companies/{companyId}/secrets",
    pathFields: ["companyId"],
    queryFields: [],
    bodyFields: [],
    bodyObjectField: "secret",
    outputField: "secret",
    inputSchema: s.actionInput(
      {
        companyId,
        secret: s.looseRequiredObject(
          "The Paperclip-managed secret to create. Extra fields supported by the connected Paperclip version are preserved.",
          {
            name: s.nonWhitespaceString("The display name of the secret."),
            value: s.nonEmptyString("The secret value."),
            key: s.nonWhitespaceString("An optional stable environment-variable key."),
            description: s.nullableString("An optional description."),
          },
          { optional: ["key", "description"] },
        ),
      },
      ["companyId", "secret"],
    ),
    outputSchema: wrappedOutput("secret", "The created Paperclip secret metadata.", objectResult("Secret data.")),
  },
];
