export const microsoftTeamsProviderScopes = {
  userRead: "User.Read",
  userReadBasicAll: "User.ReadBasic.All",
  teamReadBasicAll: "Team.ReadBasic.All",
  channelReadBasicAll: "Channel.ReadBasic.All",
  channelMessageReadAll: "ChannelMessage.Read.All",
  channelMessageSend: "ChannelMessage.Send",
  presenceReadWrite: "Presence.ReadWrite",
  chatRead: "Chat.Read",
  chatCreate: "Chat.Create",
  chatMessageSend: "ChatMessage.Send",
  filesReadWriteAll: "Files.ReadWrite.All",
  sitesReadWriteAll: "Sites.ReadWrite.All",
  offlineAccess: "offline_access",
} as const;

export const microsoftTeamsOAuthScopes: string[] = [
  microsoftTeamsProviderScopes.userRead,
  microsoftTeamsProviderScopes.userReadBasicAll,
  microsoftTeamsProviderScopes.teamReadBasicAll,
  microsoftTeamsProviderScopes.channelReadBasicAll,
  microsoftTeamsProviderScopes.channelMessageReadAll,
  microsoftTeamsProviderScopes.channelMessageSend,
  microsoftTeamsProviderScopes.presenceReadWrite,
  microsoftTeamsProviderScopes.chatRead,
  microsoftTeamsProviderScopes.chatCreate,
  microsoftTeamsProviderScopes.chatMessageSend,
  microsoftTeamsProviderScopes.filesReadWriteAll,
  microsoftTeamsProviderScopes.sitesReadWriteAll,
  microsoftTeamsProviderScopes.offlineAccess,
];
