import type {
  AgentConnectionSummary,
  AgentModelOption,
  AgentRuntimeSettings,
  AppData,
  ProviderDefinition,
} from "./model";
import type { FormEvent, ReactNode } from "react";

import { Bot, CheckCircle2, ExternalLink, KeyRound, Loader2, Save, ShieldCheck, Terminal, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "react-router";
import { apiDelete, apiPut } from "./api";
import { Badge, FormStatus, ProviderIcon } from "./shared-ui";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

interface AgentsPageProps {
  data: AppData;
  onRefresh(): void;
}

export function AgentsPage(props: AgentsPageProps): ReactNode {
  const anthropicProvider = props.data.providers.find((provider) => provider.service === "anthropic");
  const claudeConnection = props.data.agentConnections?.find((connection) => connection.provider === "claude_code");
  const claudeSettings = props.data.agentSettings?.find((settings) => settings.provider === "claude_code");

  return (
    <div className="agents-page">
      <section className="agents-intro">
        <div>
          <span className="agents-eyebrow">
            <Bot size={14} />
            Agent runtimes
          </span>
          <h2>Set up the agents that operate your Flows</h2>
          <p>
            Agent credentials stay in the connector credential store. Each Flow separately controls which connector
            tools the agent can use and which calls require approval.
          </p>
        </div>
        <Button variant="outline" asChild>
          <Link to="/providers">
            Manage connector providers
            <ExternalLink size={14} />
          </Link>
        </Button>
      </section>

      <Alert>
        <ShieldCheck size={16} />
        <AlertTitle>Claude uses your subscription</AlertTitle>
        <AlertDescription>
          Claude Code runs with a subscription OAuth token generated by its own CLI. The credential is never exposed to
          Flow tools.
        </AlertDescription>
      </Alert>

      <div className="agent-card-grid">
        <ClaudeSubscriptionCard
          provider={anthropicProvider}
          connection={claudeConnection}
          settings={claudeSettings}
          models={props.data.agentModels ?? []}
          onRefresh={props.onRefresh}
        />
      </div>
    </div>
  );
}

function ClaudeSubscriptionCard(props: {
  provider: ProviderDefinition | undefined;
  connection: AgentConnectionSummary | undefined;
  settings: AgentRuntimeSettings | undefined;
  models: AgentModelOption[];
  onRefresh(): void;
}): ReactNode {
  const [oauthToken, setOauthToken] = useState("");
  const [busy, setBusy] = useState<"save" | "delete" | null>(null);
  const [status, setStatus] = useState<string | null>(null);

  async function save(event: FormEvent): Promise<void> {
    event.preventDefault();
    setBusy("save");
    setStatus(null);
    try {
      await apiPut("/api/agent-connections/claude_code", {
        oauthToken: oauthToken.trim(),
      });
      setOauthToken("");
      setStatus("Claude subscription token saved. Claude Code selected subscription OAuth.");
      props.onRefresh();
    } catch (caught) {
      setStatus(caught instanceof Error ? caught.message : "Could not save the Claude subscription token.");
    } finally {
      setBusy(null);
    }
  }

  async function disconnect(): Promise<void> {
    if (!window.confirm("Disconnect the Claude subscription from this runtime?")) {
      return;
    }
    setBusy("delete");
    setStatus(null);
    try {
      await apiDelete("/api/agent-connections/claude_code");
      setStatus("Claude subscription connection removed.");
      props.onRefresh();
    } catch (caught) {
      setStatus(caught instanceof Error ? caught.message : "Could not remove the Claude subscription connection.");
    } finally {
      setBusy(null);
    }
  }

  return (
    <AgentCardShell
      provider={props.provider}
      eyebrow="Anthropic agent"
      name="Claude Code"
      connected={Boolean(props.connection)}
      description="Runs isolated Flow turns against the usage included with your Claude subscription."
    >
      <AgentDetails runtime="Claude Code CLI" authentication="Claude subscription OAuth" support="Ready for Flows" />
      <AgentModelSettings
        provider="claude_code"
        settings={props.settings}
        models={props.models}
        onRefresh={props.onRefresh}
      />

      <div className="claude-setup-steps">
        <div className="claude-setup-command">
          <Terminal size={15} />
          <code>claude setup-token</code>
        </div>
        <ol>
          <li>Run the command on a machine where Claude Code is installed.</li>
          <li>Complete sign-in with your Claude Pro, Max, Team, or Enterprise account.</li>
          <li>Paste the printed long-lived token below. The connector stores it and never shows it again.</li>
        </ol>
      </div>

      <form className="agent-auth-form" onSubmit={(event) => void save(event)}>
        <Label className="field">
          <span>{props.connection ? "Replace subscription token" : "Subscription OAuth token"}</span>
          <Input
            type="password"
            value={oauthToken}
            placeholder="Paste the token printed by claude setup-token"
            autoComplete="off"
            onChange={(event) => setOauthToken(event.target.value)}
            required
          />
        </Label>
        <div className="button-row">
          <Button type="submit" disabled={!oauthToken.trim() || busy !== null}>
            {busy === "save" ? <Loader2 className="spin" size={14} /> : <KeyRound size={14} />}
            {props.connection ? "Replace token" : "Connect subscription"}
          </Button>
          {props.connection ? (
            <Button variant="ghost" type="button" disabled={busy !== null} onClick={() => void disconnect()}>
              {busy === "delete" ? <Loader2 className="spin" size={14} /> : <Trash2 size={14} />}
              Disconnect
            </Button>
          ) : null}
        </div>
      </form>

      {status ? <FormStatus message={status} /> : null}
      <AgentReadiness ready={Boolean(props.connection)}>
        {props.connection
          ? "Available in the Flow builder as a Claude subscription agent."
          : "Connect your subscription token to use Claude Code in a Flow."}
      </AgentReadiness>
    </AgentCardShell>
  );
}

function AgentCardShell(props: {
  provider: ProviderDefinition | undefined;
  eyebrow: string;
  name: string;
  connected: boolean;
  description: string;
  children: ReactNode;
}): ReactNode {
  return (
    <article className="agent-app-card">
      <div className="agent-app-heading">
        <div className="agent-app-identity">
          {props.provider ? (
            <ProviderIcon provider={props.provider} large />
          ) : (
            <span className="agent-app-fallback">
              <Bot size={22} />
            </span>
          )}
          <div>
            <span>{props.eyebrow}</span>
            <h3>{props.name}</h3>
          </div>
        </div>
        <Badge tone={props.connected ? "success" : undefined}>{props.connected ? "Connected" : "Not connected"}</Badge>
      </div>
      <p className="agent-app-description">{props.description}</p>
      {props.children}
    </article>
  );
}

function AgentDetails(props: { runtime: string; authentication: string; support: string }): ReactNode {
  return (
    <dl className="agent-app-details">
      <div>
        <dt>Runtime</dt>
        <dd>{props.runtime}</dd>
      </div>
      <div>
        <dt>Authentication</dt>
        <dd>{props.authentication}</dd>
      </div>
      <div>
        <dt>Flow support</dt>
        <dd>{props.support}</dd>
      </div>
    </dl>
  );
}

function AgentModelSettings(props: {
  provider: AgentRuntimeSettings["provider"];
  settings: AgentRuntimeSettings | undefined;
  models: AgentModelOption[];
  onRefresh(): void;
}): ReactNode {
  const [model, setModel] = useState(props.settings?.model ?? props.models[0]?.id ?? "");
  const [busy, setBusy] = useState(false);
  const [status, setStatus] = useState<string | null>(null);

  useEffect(() => {
    setModel(props.settings?.model ?? props.models[0]?.id ?? "");
  }, [props.models, props.settings?.model]);

  async function save(event: FormEvent): Promise<void> {
    event.preventDefault();
    setBusy(true);
    setStatus(null);
    try {
      await apiPut<AgentRuntimeSettings>(`/api/agent-settings/${props.provider}`, {
        model: model.trim(),
      });
      setStatus("Agent model saved. Future Flow runs will use this model.");
      props.onRefresh();
    } catch (caught) {
      setStatus(caught instanceof Error ? caught.message : "Could not save the agent model.");
    } finally {
      setBusy(false);
    }
  }

  return (
    <form className="agent-model-form" onSubmit={(event) => void save(event)}>
      <div className="agent-model-heading">
        <div>
          <strong>Flow model</strong>
          <p>Read from Anthropic and used by every new Flow run.</p>
        </div>
      </div>
      <div className="agent-model-controls">
        <Label className="field">
          <span>Anthropic model</span>
          <select
            className="agent-model-select"
            value={model}
            onChange={(event) => setModel(event.target.value)}
            required
          >
            {props.models.map((option) => (
              <option key={option.id} value={option.id}>
                {option.displayName}
              </option>
            ))}
          </select>
        </Label>
        <Button
          variant="outline"
          type="submit"
          disabled={!model.trim() || props.models.length === 0 || busy || model.trim() === props.settings?.model}
        >
          {busy ? <Loader2 className="spin" size={14} /> : <Save size={14} />}
          {busy ? "Saving…" : "Save model"}
        </Button>
      </div>
      {status ? <FormStatus message={status} /> : null}
    </form>
  );
}

function AgentReadiness(props: { ready: boolean; children: ReactNode }): ReactNode {
  return (
    <div className={props.ready ? "agent-readiness ready" : "agent-readiness"}>
      {props.ready ? <CheckCircle2 size={15} /> : <Bot size={15} />}
      <span>{props.children}</span>
    </div>
  );
}
